### ISSUE TITLE
Display average adjusted win-rate against all characters when a player visits their matchup page

### ISSUE THREAD

**Issue by djgonza1** [halvnykterist/rating-update#14]
Hello, 

I love your website! 

Any chance we could get an average adjusted win rate vs all characters when a player browses their matchup % page? 
It might help to give players a notion on how fast we are projected to rank up.

**Comment by halvnykterist** [comment]
I could, although average adjusted should pretty much always be near 50%, since if you were above that you'd be gaining rating which affects the adjusted win rates. 

If you're wondering how close you are to ranking up in the tower, that's actually based on short win streaks, same as Celestial. You just need to win 5/6 games in a non-rotating buffer.

**Comment by halvnykterist** [comment]
This is now implemented!
