### ISSUE TITLE
Negative rating?

### ISSUE THREAD

**Issue by voidlily** [halvnykterist/rating-update#2]
http://ratingupdate.info/player/2EC48815DA563A7/HA

At the time I played against this person, they had a negative rating. Is this supposed to be possible?

**Comment by halvnykterist** [comment]
Yep! 0 isn't a special number and starting at 1500 is just a convention based on earlier chess rating systems. 
"Natural" rating actually has zero as its midpoint, and is adjusted to the 1500 scale for display purposes.

The only thing that matters is difference between two ratings, so in your case 2300. That's a lot, but on the other hand they've pretty much only lost and have high deviation.

It does seem to have broken my display math a bit, I think because the range is so extreme. For there to actually be a 2300 rating between you two that'd mean you're likely to win a million out of a million games against them, which seems unlikely.
