### ISSUE TITLE
get_replay is not working

### ISSUE THREAD

**Issue by nemasu** [halvnykterist/rating-update#38]
Calls to get_replay result in
```
[
  [
    "hexstring",
    1,
    "2023/07/10 06:36:18",
    "0.2.1",
    "0.0.2",
    "0.0.2",
    "",
    ""
  ],
  [
    3
  ]
]
```
I've seen 3 and 4 in that last part instead of the replay data. Which I'm guessing is an error.

I checked a real request to get_replay and there's no change, so I tried using a real token, that worked.

Looks like auth_ticket has changed.
Before the auth_ticket was:
```
<auth_ticket> structure:
    <game_token_length>
    <game_token>
    <session_size> (always equals 24)
    <unknown_1> (always equals 1)
    <unknown_2> (always equals 2)
    <ip_address> (obfuscated ip address, I suppose just <auth_ticket> identifier)
    <unknown_3> (random number, but 0 working for me)
    <connection_time> (time of session in milliseconds)
    <connection_count>

eg:
14000000 token len
5088EF43300E7A510FF1DD0B0100100162EDB663 token
18000000 24
01000000 1
02000000 2
82EC43A9 IP
7F211FB1 random (we set to 0)
EB546E03 (time of session in milliseconds)
03000000 connection count
```

now it looks like:
```
<auth_ticket> structure:
    <game_token_length>
    <game_token>
    <session_size> (always equals 24)
    <unknown_1> (always equals 1)
    <unknown_2> (always equals 5)
    <unknown_3> ?
    <unknown_4> ?
    <connection_time> (might be the same)
    <connection_count> (probably the same)

eg:
14000000 = token length = 20
42E208184E0874EC4F317E00010010014BB9AB64 = token
18000000 = session_size = 24
01000000 = 1
05000000 = 5 (used to be 2, maybe this is a version?)
14D2C326 = ? not my ip
110F0B5E = random?
D951E500 = might still be session time
05000000 = probably still connection count
```

My IP address does show up later in the app_ticket, and it seems like it never used to.
So I'm guessing they got rid of it from the auth_ticket and replaced it with ... something.

**Comment by alestef** [comment]
I don't know how helpful this is, but the **14D2C326** sequence translates to 20.210.195.38, which geolocation websites identify as a Microsoft Azure address in Tokyo. Could it one of the game's cloud-hosted services?

**Comment by nemasu** [comment]
@alestef That is interesting, thank you.

I tried using that IP there, plus I tried using 110F0B5E for the random value, then I tried 00000000 for the random value.
All didn't work :(

**Comment by collinsjacob127** [comment]
Hi, I've been looking at all this and figured I should post some relevant links in case anyone else is trying to get it fixed since the dev posted about it on Twitter;

Here is a discussion for Totsugeki where a lot of the underlying mechanics here are discussed: [Broken by December Patch?](https://github.com/optix2000/totsugeki/issues/86#issuecomment-1386032942)

It looks like people are using [proxifier](https://www.proxifier.com/) to proxy all (Or just GGST) traffic through to [polarproxy](https://www.netresec.com/?page=PolarProxy) which decrypts & writes to a .pcap file for inspection in [wireshark](https://www.wireshark.org/). These tools would probably be helpful to someone better versed with Netcode shenanigans, but I'm mainly trying to build a jumping-off point for anyone trying to get this working.

Also, @nemasu and @alestef, thank you both so much for trying to get this figured out; could either of you please elaborate on what & where in the code you're making changes to test these things? I've been having some trouble getting rating-update to run on my machine in the first place, much less changing header contents to fit the updated API.

It looks like the game_token mentioned is token.txt, made by running generate_steam_token.py. This is then used in generate_replay_request as part of the header. Is int1 in the RequestHeader struct the one that has now been changed from (always equals 2) to (always equals 5), or is this not a struct that should even be touched for this issue? Regardless, it doesn't feel like this is the most effective way for me to do testing, are y'all just using the Python code for building/sending a request mentioned [here](https://github.com/optix2000/totsugeki/issues/86#issuecomment-1363386615)?

Sorry for the long post, any advice would be greatly appreciated.

**Comment by halvnykterist** [comment]
@collinsjacob127 You should be able to just test using the python code - it has a function both for logging in and generating a token as well as fetching replays. The thing I've done in the past is used the python code to figure out what's going on and then just mirrored the changes in the replay API in the rust code, while still using the token generated from python (rust doesn't have the equivalent steam libraries, so logging in isn't possible)

**Comment by collinsjacob127** [comment]
@halvnykterist Just curious, how did you end up getting it fixed? Browsing the changes it looks like in the struct you updated the user ID from a string to an int but that seems almost too easy? Was that all that changed with get_replay?

**Comment by nemasu** [comment]
RU now uses steamworks, no need to reverse engineer this.
